apiVersion: apps/v1
kind: Deployment
metadata:
  name: stellarnet
  namespace: stellarnet-namespace
  labels:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: stellarnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: webserver
      app.kubernetes.io/part-of: stellarnet
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webserver
        app.kubernetes.io/part-of: stellarnet
    spec:
      containers:
      - name: stellarnet
        image: docker.io/stellarchaos/stellarnet:v1.3
        imagePullPolicy: Always  
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 443
          name: websecure
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
