apiVersion: apps/v1
kind: Deployment
metadata:
  name: stellarnet
  namespace: stellarnet-namespace  # Ensure this matches the namespace where your service and ingress are deployed
  labels:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: stellarnet
spec:
  replicas: 2  # Ensuring high availability
  selector:
    matchLabels:
      app.kubernetes.io/component: webserver
      app.kubernetes.io/part-of: stellarnet
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webserver
        app.kubernetes.io/part-of: stellarnet
    spec:
      containers:
      - name: stellarnet
        image: stellarchaos/stellarnet:latest
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 443
          name: websecure
          protocol: TCP
          
