# nginx-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: stellarnet-namespace
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;

        server {
            listen 80;
            server_name localhost;

            # Serve your website files
            root /usr/share/nginx/html;
            index index.html index.htm;

            # Proxy the Icecast stream
            location /stream {
                proxy_pass http://icecast-service.icecast-namespace.svc.cluster.local:8000/live;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            # Proxy the Icecast metadata and enable CORS
            location /stream-metadata {
                proxy_pass http://icecast-service.icecast-namespace.svc.cluster.local:8000/status-json.xsl;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;

                # Add CORS headers
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

                if ($request_method = 'OPTIONS') {
                    return 204;
                }
            }

            # Additional configurations if necessary
        }
    }

